### ISSUE TITLE
CronExprParser Exception

### ISSUE THREAD

**Issue by BnitoBzh** [yalesov/zf2-cron#5]
My application throw an exception for one cron task :
( The application has thrown an exception!)
(======================================================================)
( invalid cron expression component: expecting numeric or valid string, "30" given)
( Heartsentwined\CronExprParser\Exception\InvalidArgumentException)
(======================================================================)
(/home/bas/vendor/heartsentwined/cron-expr-parser/src/Heartsentwined/CronExprParser/Parser.php:149)
(----------------------------------------------------------------------)
(#0 /home/bas/vendor/heartsentwined/cron-expr-parser/src/Heartsentwined/CronExprParser/Parser.php(52): Heartsentwined\CronExprParser\Parser::matchTimeComponent('30', 35))
(#1 /home/bas/vendor/heartsentwined/zf2-cron/src/Heartsentwined/Cron/Service/Cron.php(284): Heartsentwined\CronExprParser\Parser::matchTime(1369902900, '30 6 * * *'))
(#2 /home/bas/vendor/heartsentwined/zf2-cron/src/Heartsentwined/Cron/Service/Cron.php(160): Heartsentwined\Cron\Service\Cron->schedule())
(#3 /home/bas/vendor/heartsentwined/zf2-cron/src/Heartsentwined/Cron/Controller/CronController.php(35): Heartsentwined\Cron\Service\Cron->run())
(#4 /home/bas/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Heartsentwined\Cron\Controller\CronController->indexAction())
(#5 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)))
(#6 /home/bas/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(472): call_user_func(Array, Object(Zend\Mvc\MvcEvent)))
(#8 /home/bas/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)))
(#7 /home/bas/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)))
(#9 /home/bas/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response)))
(#10 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)))
(#11 /home/bas/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(472): call_user_func(Array, Object(Zend\Mvc\MvcEvent)))
(#12 /home/bas/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)))
(#13 /home/bas/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(294): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)))
(#14 /home/bas/public/index.php(13): Zend\Mvc\Application->run())
(#15 {main})
(======================================================================)
( Previous Exception(s):)
()
(======================================================================)

I register my cron task like this :
Cron::register(
            'import-all',
            '30 6 * * *',
            array($this, 'runImport'),
            array('all')
        );

For example, this register request worked fine :
Cron::register(
            'import-queue',
            '*/30 * * * *',
            array($this, 'runImport'),
            array('queue')
        );

And my composer is configured like this :

        "heartsentwined/yaml": "1.*",
        "heartsentwined/zf2-cron": "2.*",
        "zendframework/zendframework": "2.*",
        "heartsentwined/arg-validator": "1.*",
        "heartsentwined/background-exec": "1.*",
        "heartsentwined/zf2-doctrine": "1.*",
        "heartsentwined/cron-expr-parser": "1.*",

Could you help me please ?

**Comment by yalesov** [comment]
Fixed upstream at yalesov/php-cron-expr-parser#1
